### ISSUE TITLE
Optimize discussions performance

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#1563]
## Description
As a User I want to have robust and smooth discussions operations. 

## Acceptance criteria

Based on some performance tests done one DEV env. and all the optimizations applied, the result with respect to `postDiscussionComment`, haven't improved.

Below are results from the time before / after code optimization:
### Before:
 - Number of assigned users = **60;** 
 - Number of real users creating requests: **5**
 - Number of comments per user = **30;** 
 - Test duration = **3.02 minutes;** 
 - Number of requests failed = **0:**

### After:
 - Number of assigned users = **73;** 
 - Number of real users creating requests: **5**
 - Number of comments per user = **30;** 
 - Test duration = **5.07 minutes;** 
 - Number of requests failed = **0:**

_Duration is twice higher_

### Observations:
- Number of users assigned to the discussions community have an impact (as more assigned users, as slower the Test Duration for same number of requests)
- The results could be impacted from the fact, that the rooms are not removed from synapse server and garbage data is generated
- Authorization policies.

- [ ] TBD

## Additional Context
The [issue](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/test-suites/77) as part of which the tests were performed.

**Comment by Comoque1** [comment]
The following scenarios were performed against the following data

1. Environment: TEST
2. Ecoverse with 17 Challenges and 112 members 
3. Used Challenge for creating messages to discussion, with specific number of assigned users
3. 5 different Users send in 1 second ramp-up period `N` amount of messages per 1 user to an empty discussion

- [ ] Number of assigned users = 112; N = 10; test duration = 1.50 minutes; Number of requests failed = 8:

- [ ] Number of assigned users = 112; N = 20; test duration = 1.37 minutes; Number of requests failed = 7:
Error: 
`{"errors":[{"message":"[Membership] user (@ecoverse.admin=alkem.io:matrix-test.alkem.io) membership of room (!JgEdwEpjGGvXliyIeV:matrix-test.alkem.io) is not completing.","locations":[{"line":1,"column":76}],"path":["sendMessageToDiscussion"],"extensions":{"code":"MATRIX_MEMBERSHIP_ERROR","exception":{"context":"communication","stacktrace":["Error: [Membership] user (@ecoverse.admin=alkem.io:matrix-test.alkem.io) membership of room (!JgEdwEpjGGvXliyIeV:matrix-test.alkem.io) is not completing.","    at CommunicationAdapter.addUserToRoom (/usr/src/app/dist/services/platform/communication-adapter/communication.adapter.js:349:19)","    at async RoomService.sendMessage (/usr/src/app/dist/domain/communication/room/room.service.js:60:9)","    at async DiscussionService.sendMessageToDiscussion (/usr/src/app/dist/domain/communication/discussion/discussion.service.js:100:25)","    at async DiscussionResolverMutations.sendMessageToDiscussion (/usr/src/app/dist/domain/communication/discussion/discussion.resolver.mutations.js:46:35)","    at async target (/usr/src/app/node_modules/@nestjs/core/helpers/external-context-creator.js:77:28)","    at async /usr/src/app/node_modules/@nestjs/core/helpers/external-proxy.js:9:24"]}}}],"data":null}`

- [ ] Number of assigned users = 112; N = 30; test duration = 2.24 minutes; Number of requests failed = 8:

The first 2 requests for 4 users are  failing.

Results from [previous execution](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/test-suites/77):
 N = 10; test duration = 2.16 minutes; Number of requests failed = 0:
 N = 20; test duration = 3.40 minutes; Number of requests failed = 0:
 N = 30; test duration = 2.15 minutes; Number of requests failed = 0:

**Comment by Comoque1** [comment]
The following scenarios were performed against the following data

1. Environment: TEST
2. Ecoverse with 17 Challenges and 107 members 
3. Used Challenge for creating messages to discussion, with specific number of assigned users
3. 5 different Users send in 1 second ramp-up period `N` amount of messages per 1 user to an empty discussion

### New results

- [ ] Number of assigned users = 107; N = 10; **test duration = 0.10** minutes; Number of requests failed = 0:
- [ ] Number of assigned users = 107; N = 20; **test duration = 0.12** minutes; Number of requests failed = 0:
- [ ] Number of assigned users = 107; N = 30; **test duration = 0.12** minutes; Number of requests failed = 0:

### Previous results
- [ ] Number of assigned users = 112; N = 10; **test duration = 1.50** minutes; Number of requests failed = 8:
- [ ] Number of assigned users = 112; N = 20; **test duration = 1.37** minutes; Number of requests failed = 7:
- [ ] Number of assigned users = 112; N = 30; **test duration = 2.24** minutes; Number of requests failed = 8:


The first 2 requests for 4 users are  failing.

Results from [previous execution](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/test-suites/77):
 N = 10; test duration = 2.16 minutes; Number of requests failed = 0:
 N = 20; test duration = 3.40 minutes; Number of requests failed = 0:
 N = 30; test duration = 2.15 minutes; Number of requests failed = 0:
