### ISSUE TITLE
Search to include aspects in results

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1695]
## Description
As a user I want to be able to find challenges based on relevant aspects

## Acceptance criteria

- [ ] Searching on challenges, opportunities to include the title, description + tags of associated aspects

## Additional Context
Out of scope: search to also return Aspects as a result type

**Comment by valentinyanakiev** [comment]
There is no title, there is type, so replacing title with type.

**Comment by valentinyanakiev** [comment]
Switched type to displayName

**Comment by valentinyanakiev** [comment]
npm run typeorm migration:run


> alkemio-server@0.18.3 typeorm
> ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js --config src/config/typeorm.cli.config.ts "migration:run"

query: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'alkemio' AND `TABLE_NAME` = 'migrations_typeorm'
query: SELECT * FROM `alkemio`.`migrations_typeorm` `migrations_typeorm` ORDER BY `id` DESC
24 migrations are already loaded in the database.
25 migrations were found in the source code.
visual1642233654294 is the last executed migration. It was executed on Sat Jan 15 2022 10:00:54 GMT+0200 (Eastern European Standard Time).
1 migrations are new migrations that needs to be executed.
query: START TRANSACTION
query: CREATE TABLE `comments` (`id` char(36) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `version` int NOT NULL, `displayName` varchar(255) NOT NULL, `communicationGroupID` varchar(255) NOT NULL, `communicationRoomID` varchar(255) NOT NULL, `authorizationId` char(36) NULL, UNIQUE INDEX `REL_7777dccdda9ba57d8e3a634cd8` (`authorizationId`), PRIMARY KEY (`id`)) ENGINE=InnoDB
query failed: CREATE TABLE `comments` (`id` char(36) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `version` int NOT NULL, `displayName` varchar(255) NOT NULL, `communicationGroupID` varchar(255) NOT NULL, `communicationRoomID` varchar(255) NOT NULL, `authorizationId` char(36) NULL, UNIQUE INDEX `REL_7777dccdda9ba57d8e3a634cd8` (`authorizationId`), PRIMARY KEY (`id`)) ENGINE=InnoDB
error: Error: ER_TABLE_EXISTS_ERROR: Table 'comments' already exists
    at Query.Sequence._packetToError (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:375:28)
    at Socket.emit (domain.js:470:12)
    --------------------
    at Protocol._enqueue (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at PoolConnection.query (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:198:25)
    at MysqlQueryRunner.<anonymous> (/home/valentin/source/repos/alkemio/server/src/driver/mysql/MysqlQueryRunner.ts:184:36)
    at step (/home/valentin/source/repos/alkemio/server/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/valentin/source/repos/alkemio/server/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/home/valentin/source/repos/alkemio/server/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ER_TABLE_EXISTS_ERROR',
  errno: 1050,
  sqlMessage: "Table 'comments' already exists",
  sqlState: '42S01',
  index: 0,
  sql: 'CREATE TABLE `comments` (`id` char(36) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `version` int NOT NULL, `displayName` varchar(255) NOT NULL, `communicationGroupID` varchar(255) NOT NULL, `communicationRoomID` varchar(255) NOT NULL, `authorizationId` char(36) NULL, UNIQUE INDEX `REL_7777dccdda9ba57d8e3a634cd8` (`authorizationId`), PRIMARY KEY (`id`)) ENGINE=InnoDB'
}
query: ROLLBACK
Error during migration run:
QueryFailedError: ER_TABLE_EXISTS_ERROR: Table 'comments' already exists
    at QueryFailedError.TypeORMError [as constructor] (/home/valentin/source/repos/alkemio/server/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/home/valentin/source/repos/alkemio/server/src/error/QueryFailedError.ts:9:9)
    at Query.<anonymous> (/home/valentin/source/repos/alkemio/server/src/driver/mysql/MysqlQueryRunner.ts:195:37)
    at Query.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:43:10) {
  query: 'CREATE TABLE `comments` (`id` char(36) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `version` int NOT NULL, `displayName` varchar(255) NOT NULL, `communicationGroupID` varchar(255) NOT NULL, `communicationRoomID` varchar(255) NOT NULL, `authorizationId` char(36) NULL, UNIQUE INDEX `REL_7777dccdda9ba57d8e3a634cd8` (`authorizationId`), PRIMARY KEY (`id`)) ENGINE=InnoDB',
  parameters: undefined,
  driverError: Error: ER_TABLE_EXISTS_ERROR: Table 'comments' already exists
      at Query.Sequence._packetToError (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
      at Query.ErrorPacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
      at Protocol._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
      at Parser._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
      at Parser.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
      at Protocol.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
      at Socket.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:88:28)
      at Socket.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:526:10)
      at Socket.emit (events.js:375:28)
      at Socket.emit (domain.js:470:12)
      --------------------
      at Protocol._enqueue (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
      at PoolConnection.query (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:198:25)
      at MysqlQueryRunner.<anonymous> (/home/valentin/source/repos/alkemio/server/src/driver/mysql/MysqlQueryRunner.ts:184:36)
      at step (/home/valentin/source/repos/alkemio/server/node_modules/tslib/tslib.js:143:27)
      at Object.next (/home/valentin/source/repos/alkemio/server/node_modules/tslib/tslib.js:124:57)
      at fulfilled (/home/valentin/source/repos/alkemio/server/node_modules/tslib/tslib.js:114:62)
      at processTicksAndRejections (internal/process/task_queues.js:95:5) {
    code: 'ER_TABLE_EXISTS_ERROR',
    errno: 1050,
    sqlMessage: "Table 'comments' already exists",
    sqlState: '42S01',
    index: 0,
    sql: 'CREATE TABLE `comments` (`id` char(36) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `version` int NOT NULL, `displayName` varchar(255) NOT NULL, `communicationGroupID` varchar(255) NOT NULL, `communicationRoomID` varchar(255) NOT NULL, `authorizationId` char(36) NULL, UNIQUE INDEX `REL_7777dccdda9ba57d8e3a634cd8` (`authorizationId`), PRIMARY KEY (`id`)) ENGINE=InnoDB'
  },
  code: 'ER_TABLE_EXISTS_ERROR',
  errno: 1050,
  sqlMessage: "Table 'comments' already exists",
  sqlState: '42S01',
  index: 0,
  sql: 'CREATE TABLE `comments` (`id` char(36) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `version` int NOT NULL, `displayName` varchar(255) NOT NULL, `communicationGroupID` varchar(255) NOT NULL, `communicationRoomID` varchar(255) NOT NULL, `authorizationId` char(36) NULL, UNIQUE INDEX `REL_7777dccdda9ba57d8e3a634cd8` (`authorizationId`), PRIMARY KEY (`id`)) ENGINE=InnoDB'
}

**Comment by Comoque1** [comment]
Seems OK on test env. using the global search.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/4f9b57a5-8e4f-4a6a-8d7f-23da42727137)
