### ISSUE TITLE
BUG: Debug sessions on VS Code fail

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#1912]
**Describe the bug**
Debugging on VS Code fails with an error

**To Reproduce**
1. Select `Debug Alkemio Server` debug profile in VS Code
2. Hit F5

```
[NestWinston] Info      5/9/2022, 12:38:12 PM [RouterExplorer] Mapped {/rest/completeCredentialOfferInteraction/:nonce, POST} route - {}
(node:95283) UnhandledPromiseRejectionWarning: Error: Cannot determine a GraphQL output type for the "id". Make sure your class is decorated with an appropriate decorator.
    at OutputTypeFactory.create (/home/valentin/source/repos/alkemio/server/node_modules/@nestjs/graphql/dist/schema-builder/factories/output-type.factory.js:19:23)
    at /home/valentin/source/repos/alkemio/server/node_modules/@nestjs/graphql/dist/schema-builder/factories/object-type-definition.factory.js:81:53
    at Array.forEach (<anonymous>)
    at /home/valentin/source/repos/alkemio/server/node_modules/@nestjs/graphql/dist/schema-builder/factories/object-type-definition.factory.js:80:24
    at resolveThunk (/home/valentin/source/repos/alkemio/server/node_modules/graphql/type/definition.js:480:40)
    at defineFieldMap (/home/valentin/source/repos/alkemio/server/node_modules/graphql/type/definition.js:692:18)
    at GraphQLObjectType.getFields (/home/valentin/source/repos/alkemio/server/node_modules/graphql/type/definition.js:633:27)
    at TypeFieldsAccessor.extractFromInterfaceOrObjectType (/home/valentin/source/repos/alkemio/server/node_modules/@nestjs/graphql/dist/schema-builder/services/type-fields.accessor.js:24:32)
    at /home/valentin/source/repos/alkemio/server/node_modules/@nestjs/graphql/dist/schema-builder/factories/object-type-definition.factory.js:103:66
    at resolveThunk (/home/valentin/source/repos/alkemio/server/node_modules/graphql/type/definition.js:480:40)
    at defineFieldMap (/home/valentin/source/repos/alkemio/server/node_modules/graphql/type/definition.js:692:18)
    at GraphQLObjectType.getFields (/home/valentin/source/repos/alkemio/server/node_modules/graphql/type/definition.js:633:27)
    at collectReferencedTypes (/home/valentin/source/repos/alkemio/server/node_modules/graphql/type/schema.js:366:81)
    at new GraphQLSchema (/home/valentin/source/repos/alkemio/server/node_modules/graphql/type/schema.js:148:9)
    at GraphQLSchemaFactory.create (/home/valentin/source/repos/alkemio/server/node_modules/@nestjs/graphql/dist/schema-builder/graphql-schema.factory.js:39:24)
    at GraphQLSchemaBuilder.generateSchema (/home/valentin/source/repos/alkemio/server/node_modules/@nestjs/graphql/dist/graphql-schema.builder.js:36:52)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:95283) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:95283) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
The application starts normally

**Comment by valentinyanakiev** [comment]
introduced in 28ac2f2eaed8647cbe0a7e499f22db0d8c50e476
