### ISSUE TITLE
Apply findings from analysis work of Alkemio schema

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2360]
## Description
As an admin I want to have confidence that the design of the db is robust

## Acceptance criteria
- [ ] Review of all findings from schema review, including suggested migration
- [ ] Apply findings via migration

## Additional Context

https://hackmd.io/na068Oq0R_WPlLE7Y0f0ag

**Comment by Comoque1** [comment]
Create group on community fails:
```
{
  "errors": [
    {
      "message": "ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`alkemio`.`user_group`, CONSTRAINT `FK_9fcc131f256e969d773327f07cb` FOREIGN KEY (`communityId`) REFERENCES `community` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION)",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createGroupOnCommunity"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "query": "INSERT INTO `user_group`(`id`, `createdDate`, `updatedDate`, `version`, `name`, `hubID`, `authorizationId`, `profileId`, `organizationId`, `communityId`) VALUES (?, DEFAULT, DEFAULT, 1, ?, ?, ?, ?, DEFAULT, DEFAULT)",
          "parameters": [
            "97a8a6fb-947c-431e-ad85-74193ce1326f",
            "234",
            "7e3c4b24-ee1b-44e8-948b-7b9909164b28",
            "a869e35d-ded6-4ed6-a4ad-d6f5b9975316",
            "5c6bd2b3-f41a-40a1-893b-f1b9539040f1"
          ],
          "driverError": {
            "code": "ER_NO_REFERENCED_ROW_2",
            "errno": 1452,
            "sqlMessage": "Cannot add or update a child row: a foreign key constraint fails (`alkemio`.`user_group`, CONSTRAINT `FK_9fcc131f256e969d773327f07cb` FOREIGN KEY (`communityId`) REFERENCES `community` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION)",
            "sqlState": "23000",
            "index": 0,
            "sql": "INSERT INTO `user_group`(`id`, `createdDate`, `updatedDate`, `version`, `name`, `hubID`, `authorizationId`, `profileId`, `organizationId`, `communityId`) VALUES ('97a8a6fb-947c-431e-ad85-74193ce1326f', DEFAULT, DEFAULT, 1, '234', '7e3c4b24-ee1b-44e8-948b-7b9909164b28', 'a869e35d-ded6-4ed6-a4ad-d6f5b9975316', '5c6bd2b3-f41a-40a1-893b-f1b9539040f1', DEFAULT, DEFAULT)"
          },
          "code": "ER_NO_REFERENCED_ROW_2",
          "errno": 1452,
          "sqlMessage": "Cannot add or update a child row: a foreign key constraint fails (`alkemio`.`user_group`, CONSTRAINT `FK_9fcc131f256e969d773327f07cb` FOREIGN KEY (`communityId`) REFERENCES `community` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION)",
          "sqlState": "23000",
          "index": 0,
          "sql": "INSERT INTO `user_group`(`id`, `createdDate`, `updatedDate`, `version`, `name`, `hubID`, `authorizationId`, `profileId`, `organizationId`, `communityId`) VALUES ('97a8a6fb-947c-431e-ad85-74193ce1326f', DEFAULT, DEFAULT, 1, '234', '7e3c4b24-ee1b-44e8-948b-7b9909164b28', 'a869e35d-ded6-4ed6-a4ad-d6f5b9975316', '5c6bd2b3-f41a-40a1-893b-f1b9539040f1', DEFAULT, DEFAULT)",
          "stacktrace": [
            "QueryFailedError: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`alkemio`.`user_group`, CONSTRAINT `FK_9fcc131f256e969d773327f07cb` FOREIGN KEY (`communityId`) REFERENCES `community` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION)",
            "    at QueryFailedError.TypeORMError [as constructor] (/home/como/repos/z/server/src/error/TypeORMError.ts:7:9)",
            "    at new QueryFailedError (/home/como/repos/z/server/src/error/QueryFailedError.ts:9:9)",
            "    at Query.<anonymous> (/home/como/repos/z/server/src/driver/mysql/MysqlQueryRunner.ts:196:37)",
            "    at Query.<anonymous> (/home/como/repos/z/server/node_modules/mysql/lib/Connection.js:526:10)",
            "    at Query._callback (/home/como/repos/z/server/node_modules/mysql/lib/Connection.js:488:16)",
            "    at Query.Sequence.end (/home/como/repos/z/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)",
            "    at Query.ErrorPacket (/home/como/repos/z/server/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)",
            "    at Protocol._parsePacket (/home/como/repos/z/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)",
            "    at Parser._parsePacket (/home/como/repos/z/server/node_modules/mysql/lib/protocol/Parser.js:433:10)",
            "    at Parser.write (/home/como/repos/z/server/node_modules/mysql/lib/protocol/Parser.js:43:10)",
            "    at Protocol.write (/home/como/repos/z/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)",
            "    at Socket.<anonymous> (/home/como/repos/z/server/node_modules/mysql/lib/Connection.js:88:28)",
            "    at Socket.<anonymous> (/home/como/repos/z/server/node_modules/mysql/lib/Connection.js:526:10)",
            "    at Socket.emit (node:events:527:28)",
            "    at addChunk (node:internal/streams/readable:315:12)",
            "    at readableAddChunk (node:internal/streams/readable:289:9)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Comment by Comoque1** [comment]
Community member (NOT ADMIN), cannot send comments to its community.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/647879a6-90f5-4463-9d1e-d6dbaa3d69d9)

**Comment by techsmyth** [comment]
@Comoque1 it feels very strange if the db update gave the above error...
