### ISSUE TITLE
BUG: Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3728]
**Describe the bug**

**To Reproduce**
1. Go to https://kibana.alkem.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-24h%2Fh,to:now))&_a=(columns:!(message,err.code,code,stack),filters:!(),index:ee214087-bb19-4337-b7ec-a593912a6afd,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))
2. Deadlock was reported on the system.
<img width="1694" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNi93QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5330fa7013eb6d3f24642c53a9a19fbbd8e955c4/image.png" alt="image.png" />

```
QueryFailedError: Deadlock found when trying to get lock; try restarting transaction at Query.onResult (/usr/src/app/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:158:37) at Query.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:36:14) at PoolConnection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:456:32) at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:85:12) at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16) at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:92:25) at Socket.emit (node:events:527:28) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at Socket.Readable.push (node:internal/streams/readable:228:10) at TCP.onStreamRead (node:internal/stream_base_commons:190:23)



```

**Expected behavior**
TBD

**Comment by DonnaDuiker** [comment]
Seems not to be occuring anymore


https://kibana.alkem.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-1y%2Fd,to:now))&_a=(columns:!('@timestamp',message,level),dataSource:(dataViewId:ee214087-bb19-4337-b7ec-a593912a6afd,type:dataView),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'906040b3-49db-4cb2-895c-ebaa2a3aac9c',key:message,negate:!f,params:(query:'%22Deadlock*%22'),type:phrase),query:(match_phrase:(message:'%22Deadlock*%22')))),hideChart:!f,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))
