### ISSUE TITLE
BUG: When you invite a VC to subspace and it's already part of the parent community the server throws an error

### ISSUE THREAD

**Issue by bobbykolev** [cherrytwist/Server#4223]
**Describe the bug**
Invite an external VC to a subspace, then invite the same vc to another subspace of the same space. The server throws an error and the user is unable to accept the invite.

**To Reproduce**
1. Invite externla VC to subspace.
2. Accept this invite (should be successful and the VC is now part of the space and subspace).
3. Invite the same VC to another subspace from the same space.
4. Try to accept the invte
4. See the error (server)

**Expected behavior**
The host of a VC should be able to accept all invites and a VC should be able to be part of multiple subspaces under the same space.

**Screenshots**
<img width="1222" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEs4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c940640fed67bcc56d6f159cedd9131942f31c0/afbeelding%20%281%29.png" alt="afbeelding (1).png" />

**Additional context**

Local server logs. It looks like the logic for assiging the VC to the parent space is failing as it's already part of it.

```

C:\Users\Vision\Downloads\work\Alkemio\project\server\src\common\exceptions\user.input.error.ts:6   
    super(message, {
    ^
GraphQLError: Agent (virtual-vctoinvite) already has assigned credential: space-member
    at new UserInputError (C:\Users\Vision\Downloads\work\Alkemio\project\server\src\common\exceptions\user.input.error.ts:6:5)
    at new ValidationException (C:\Users\Vision\Downloads\work\Alkemio\project\server\src\common\exceptions\validation.exception.ts:7:5)
    at AgentService.grantCredential (C:\Users\Vision\Downloads\work\Alkemio\project\server\src\domain\agent\agent\agent.service.ts:193:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CommunityService.assignContributorAgentToRole (C:\Users\Vision\Downloads\work\Alkemio\project\server\src\domain\community\community\community.service.ts:1071:12)
    at CommunityService.assignVirtualToRole (C:\Users\Vision\Downloads\work\Alkemio\project\server\src\domain\community\community\community.service.ts:710:32)
    at CommunityService.assignContributorToRole (C:\Users\Vision\Downloads\work\Alkemio\project\server\src\domain\community\community\community.service.ts:581:16)
    at communityAddMember (C:\Users\Vision\Downloads\work\Alkemio\project\server\src\domain\community\community\community.lifecycle.invitation.options.provider.ts:114:15)
PS C:\Users\Vision\Downloads\work\Alkemio\project\server>

**Comment by SimoneZaza** [comment]
It seems like the VC actually did become a member of the subspace, but of course this error needs to be fixed :) If the invitee is already a member of the parent space, the Accept button should just add them as a member of the subspace and disregard the parent space.

**Comment by Comoque1** [comment]
Tested OK on dev env.
