### ISSUE TITLE
BUG: Server crashes when an exception is thrown inside an XState action

### ISSUE THREAD

**Issue by bobbykolev** [cherrytwist/Server#4618]
**Describe the bug**
Any exception thrown inside an XState action is causing the server to crash

e.g. On accepting a Lead role to a community where the Lead limit is reached (2) the server crashes.

**To Reproduce**
1. Go to community settings and add to leads;
2. Send an invite to a 3rd user (as lead again);
3. Accept the invite with that user;
4. See the error (expected - limit reach), however the server crashes;

**Expected behavior**
The server should NOT crash if an exception is thrown in the XState actions.
Stretch: user receives a meaningful message about what happened. 

**Screenshots**

**Additional context**
Stack trace:

```
C:\Users\Vision\Downloads\work\Alkemio\project\server\src\common\exceptions\base.exception.ts:15
    super(message, {
    ^


RoleSetPolicyRoleLimitsException: Max limit of users reached for role 'lead': 2, cannot assign new user.
    at BaseException (C:\Users\Vision\Downloads\work\Alkemio\project\server\src\common\exceptions\base.exception.ts:15:5)
    at RoleSetPolicyRoleLimitsException (C:\Users\Vision\Downloads\work\Alkemio\project\server\src\common\exceptions\role.set.policy.role.limits.exception.ts:6:5)
    at RoleSetService.validateUserCommunityPolicy (C:\Users\Vision\Downloads\work\Alkemio\project\server\src\domain\access\role-set\role.set.service.ts:780:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at RoleSetService.validateCommunityPolicyLimits (C:\Users\Vision\Downloads\work\Alkemio\project\server\src\domain\access\role-set\role.set.service.ts:839:7)
    at RoleSetService.assignContributorAgentToRole (C:\Users\Vision\Downloads\work\Alkemio\project\server\src\domain\access\role-set\role.set.service.ts:851:5)
    at RoleSetService.assignUserToRole (C:\Users\Vision\Downloads\work\Alkemio\project\server\src\domain\access\role-set\role.set.service.ts:494:18)
    at RoleSetService.assignContributorToRole (C:\Users\Vision\Downloads\work\Alkemio\project\server\src\domain\access\role-set\role.set.service.ts:443:16)
    at communityAddMember (C:\Users\Vision\Downloads\work\Alkemio\project\server\src\domain\access\role-set\role.set.lifecycle.invitation.options.provider.ts:131:15) {
  path: undefined,
  locations: undefined,
  extensions: {
    code: 'COMMUNITY_POLICY_ROLE_LIMITS_VIOLATED',
    context: 'community',
    errorId: '9c0ec9f4-95ff-4d15-b7be-38e3a7909a3b',
    details: undefined
  },
  context: 'community',
  code: 'COMMUNITY_POLICY_ROLE_LIMITS_VIOLATED',
  details: undefined,
  errorId: '9c0ec9f4-95ff-4d15-b7be-38e3a7909a3b',
  exceptionName: 'RoleSetPolicyRoleLimitsException'
}
```

Relates to: https://github.com/alkem-io/server/pull/4613

**Areas that will be affected as part of the fix**
_Optional, to be added by developer if relevant_

**Comment by Comoque1** [comment]
The above scenario, doesn't crash the server after the latest xstate changes, but sets the invitation in "accepting" state.
The user becomes a member, but not a lead, as the limit is reached. but the impact of this, is that the invitation cannot be removed. 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHFGQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--531c4f8fd617ea75e8bd8188313dde663ccb9593/image.png" alt="image.png" />

**Comment by valentinyanakiev** [comment]
@Comoque1 that is a very different bug to the one above - one is catastrophic unhandled failure leading to pod restart, the other one an error in the business logic, I suggest we open a separate bug for it and tag it as high priority.

**Comment by Comoque1** [comment]
Raised the bug: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/server/4653 and closing this one.
